
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<Result<Config, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConfig(config: Config) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemPrompt() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_prompt") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels(provider: string, apiKey: string, baseUrl: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models", { provider, apiKey, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory() : Promise<Result<Thread[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThread(id: string) : Promise<Result<Thread, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thread", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteThread(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_thread", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteVersion(messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_version", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreVersion(messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_version", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDeletedMessages() : Promise<Result<DeletedMessage[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_deleted_messages") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideDeletedMessage(messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_deleted_message", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateDesign(prompt: string, threadId: string | null, parentMacroCode: string | null, workingDesign: DesignOutput | null, isRetry: boolean, imageData: string | null, attachments: Attachment[] | null, questionMode: boolean | null) : Promise<Result<GenerateOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_design", { prompt, threadId, parentMacroCode, workingDesign, isRetry, imageData, attachments, questionMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initGenerationAttempt(threadId: string, prompt: string, attachments: Attachment[] | null, imageData: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_generation_attempt", { threadId, prompt, attachments, imageData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async finalizeGenerationAttempt(messageId: string, status: FinalizeStatus, design: DesignOutput | null, usage: UsageSummary | null, artifactBundle: ArtifactBundle | null, modelManifest: ModelManifest | null, errorMessage: string | null, responseText: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finalize_generation_attempt", { messageId, status, design, usage, artifactBundle, modelManifest, errorMessage, responseText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async classifyIntent(prompt: string, threadId: string | null, context: string | null, imageData: string | null, attachments: Attachment[] | null) : Promise<Result<IntentDecision, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("classify_intent", { prompt, threadId, context, imageData, attachments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderStl(macroCode: string, parameters: Partial<{ [key in string]: ParamValue }>) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_stl", { macroCode, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderModel(macroCode: string, parameters: Partial<{ [key in string]: ParamValue }>) : Promise<Result<ArtifactBundle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_model", { macroCode, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFcstd(sourcePath: string) : Promise<Result<ArtifactBundle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_fcstd", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyImportedModel(artifactBundle: ArtifactBundle, manifest: ModelManifest, parameters: Partial<{ [key in string]: ParamValue }>, messageId: string | null) : Promise<Result<ArtifactBundle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_imported_model", { artifactBundle, manifest, parameters, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelManifest(modelId: string) : Promise<Result<ModelManifest, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_manifest", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveModelManifest(modelId: string, manifest: ModelManifest, messageId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_model_manifest", { modelId, manifest, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultMacro() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_macro") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMessStlPath() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mess_stl_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportFile(sourcePath: string, targetPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_file", { sourcePath, targetPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addManualVersion(threadId: string, title: string, versionName: string, macroCode: string, parameters: Partial<{ [key in string]: ParamValue }>, uiSpec: UiSpec, artifactBundle: ArtifactBundle | null, modelManifest: ModelManifest | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_manual_version", { threadId, title, versionName, macroCode, parameters, uiSpec, artifactBundle, modelManifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addImportedModelVersion(threadId: string, title: string, artifactBundle: ArtifactBundle, modelManifest: ModelManifest) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_imported_model_version", { threadId, title, artifactBundle, modelManifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateUiSpec(messageId: string, uiSpec: UiSpec) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ui_spec", { messageId, uiSpec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateParameters(messageId: string, parameters: Partial<{ [key in string]: ParamValue }>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_parameters", { messageId, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async parseMacroParams(macroCode: string) : Promise<ParsedParamsResult> {
    return await TAURI_INVOKE("parse_macro_params", { macroCode });
},
async uploadAsset(sourcePath: string, name: string, format: string) : Promise<Result<Asset, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_asset", { sourcePath, name, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRecordedAudio(base64Data: string, name: string) : Promise<Result<Asset, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_recorded_audio", { base64Data, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastDesign() : Promise<Result<LastDesignSnapshot | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_last_design") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveLastDesign(snapshot: LastDesignSnapshot | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_last_design", { snapshot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Advisory = { advisoryId: string; label: string; severity: AdvisorySeverity; primitiveIds?: string[]; viewIds?: string[]; message: string; condition?: AdvisoryCondition; threshold?: number | null }
export type AdvisoryCondition = "always" | "below" | "above"
export type AdvisorySeverity = "info" | "warning"
export type AppError = { code: AppErrorCode; message: string; details?: string | null }
export type AppErrorCode = "validation" | "notFound" | "provider" | "persistence" | "render" | "parse" | "internal"
export type ArtifactBundle = { schemaVersion?: number; modelId: string; sourceKind: ModelSourceKind; contentHash: string; artifactVersion?: number; fcstdPath: string; manifestPath: string; macroPath?: string | null; previewStlPath: string; viewerAssets?: ViewerAsset[] }
export type Asset = { id: string; name: string; path: string; format: string }
export type Attachment = { path: string; name: string; explanation: string; kind: AttachmentKind }
export type AttachmentKind = "image" | "cad"
export type Config = { engines: Engine[]; selectedEngineId: string; freecadCmd?: string; assets?: Asset[]; microwave?: MicrowaveConfig | null }
export type ControlPrimitive = { primitiveId: string; label: string; kind: ControlPrimitiveKind; partIds?: string[]; bindings?: PrimitiveBinding[]; editable: boolean; order?: number }
export type ControlPrimitiveKind = "number" | "toggle" | "choice"
export type ControlRelation = { relationId: string; sourcePrimitiveId: string; targetPrimitiveId: string; mode: ControlRelationMode; scale?: number; offset?: number; enabled?: boolean }
export type ControlRelationMode = "mirror" | "scale" | "offset"
export type ControlView = { viewId: string; label: string; scope: ControlViewScope; partIds?: string[]; primitiveIds?: string[]; sections?: ControlViewSection[]; default?: boolean; source: ControlViewSource; status?: EnrichmentStatus; order?: number }
export type ControlViewScope = "global" | "part"
export type ControlViewSection = { sectionId: string; label: string; primitiveIds?: string[]; collapsed?: boolean }
export type ControlViewSource = "generated" | "inherited" | "llm" | "manual"
export type DeletedMessage = { id: string; threadId: string; threadTitle: string; role: MessageRole; content: string; output?: DesignOutput | null; usage?: UsageSummary | null; artifactBundle?: ArtifactBundle | null; modelManifest?: ModelManifest | null; timestamp: number; imageData?: string | null; attachmentImages?: string[]; deletedAt: number }
export type DesignOutput = { title?: string; versionName?: string; response?: string; interactionMode?: InteractionMode; macroCode: string; uiSpec?: UiSpec; initialParams?: Partial<{ [key in string]: ParamValue }> }
export type DocumentMetadata = { documentName: string; documentLabel: string; sourcePath?: string | null; objectCount?: number; warnings?: string[] }
export type Engine = { id: string; name: string; provider: string; apiKey: string; model: string; lightModel?: string; baseUrl: string; systemPrompt: string }
export type EnrichmentProposal = { proposalId: string; label: string; partIds?: string[]; parameterKeys?: string[]; confidence: number; status: EnrichmentStatus; provenance: string }
export type EnrichmentStatus = "none" | "pending" | "accepted" | "rejected"
export type EyeStyle = "dot" | "bar" | "slant"
export type FinalizeStatus = "success" | "error" | "discarded"
export type GenerateOutput = { design: DesignOutput; threadId: string; messageId: string; usage?: UsageSummary | null }
export type GenieTraits = { version?: number; seed: number; colorHue: number; vertexCount: number; radiusBase: number; stretchY: number; asymmetry: number; chordSkip: number; jitterScale: number; pulseScale: number; hoverScale: number; warpScale: number; glowHueShift: number; eyeStyle: EyeStyle; eyeSpacing: number; eyeSize: number; mouthCurve: number; thinkingBias: number; repairBias: number; renderBias: number; expressiveness: number }
export type IntentDecision = { intentMode: string; confidence: number; response: string; usage?: UsageSummary | null }
export type InteractionMode = "design" | "question"
export type LastDesignSnapshot = { design?: DesignOutput | null; threadId?: string | null; messageId?: string | null; artifactBundle?: ArtifactBundle | null; modelManifest?: ModelManifest | null; selectedPartId?: string | null }
export type ManifestBounds = { xMin: number; yMin: number; zMin: number; xMax: number; yMax: number; zMax: number }
export type ManifestEnrichmentState = { status: EnrichmentStatus; proposals?: EnrichmentProposal[] }
export type Message = { id: string; role: MessageRole; content: string; status: MessageStatus; output?: DesignOutput | null; usage?: UsageSummary | null; artifactBundle?: ArtifactBundle | null; modelManifest?: ModelManifest | null; imageData?: string | null; attachmentImages?: string[]; timestamp: number }
export type MessageRole = "user" | "assistant"
export type MessageStatus = "pending" | "success" | "error" | "discarded"
export type MicrowaveConfig = { humId?: string | null; dingId?: string | null; muted?: boolean }
export type ModelManifest = { schemaVersion?: number; modelId: string; sourceKind: ModelSourceKind; document: DocumentMetadata; parts?: PartBinding[]; parameterGroups?: ParameterGroup[]; controlPrimitives?: ControlPrimitive[]; controlRelations?: ControlRelation[]; controlViews?: ControlView[]; advisories?: Advisory[]; selectionTargets?: SelectionTarget[]; warnings?: string[]; enrichmentState?: ManifestEnrichmentState }
export type ModelSourceKind = "generated" | "importedFcstd"
export type ParamValue = string | number | boolean | null
export type ParameterGroup = { groupId: string; label: string; parameterKeys?: string[]; partIds?: string[]; editable: boolean; presentation?: string | null; order?: number | null }
export type ParsedParamsResult = { fields: UiField[]; params: Partial<{ [key in string]: ParamValue }> }
export type PartBinding = { partId: string; freecadObjectName: string; label: string; kind: string; semanticRole?: string | null; viewerAssetPath?: string | null; viewerNodeIds?: string[]; parameterKeys?: string[]; editable: boolean; bounds?: ManifestBounds | null; volume?: number | null; area?: number | null }
export type PrimitiveBinding = { parameterKey: string; scale?: number; offset?: number; min?: number | null; max?: number | null }
export type SelectOption = { label: string; value: SelectValue }
export type SelectValue = string | number
export type SelectionTarget = { partId: string; viewerNodeId: string; label: string; kind: SelectionTargetKind; editable: boolean }
export type SelectionTargetKind = "part" | "object" | "group"
export type Thread = { id: string; title: string; summary?: string; messages: Message[]; updatedAt: number; genieTraits?: GenieTraits | null; versionCount?: number; pendingCount?: number; errorCount?: number }
export type UiField = { type: "range"; key: string; label?: string; min?: number | null; max?: number | null; step?: number | null; minFrom?: string | null; maxFrom?: string | null; frozen?: boolean } | { type: "number"; key: string; label?: string; min?: number | null; max?: number | null; step?: number | null; minFrom?: string | null; maxFrom?: string | null; frozen?: boolean } | { type: "select"; key: string; label?: string; options?: SelectOption[]; frozen?: boolean } | { type: "checkbox"; key: string; label?: string; frozen?: boolean }
export type UiSpec = { fields?: UiField[] }
export type UsageSegment = { stage: string; provider: string; model: string; inputTokens?: number; outputTokens?: number; totalTokens?: number; cachedInputTokens?: number; reasoningTokens?: number; estimatedCostUsd?: number | null }
export type UsageSummary = { inputTokens?: number; outputTokens?: number; totalTokens?: number; cachedInputTokens?: number; reasoningTokens?: number; estimatedCostUsd?: number | null; segments?: UsageSegment[] }
export type ViewerAsset = { partId: string; nodeId: string; objectName: string; label: string; path: string; format: ViewerAssetFormat }
export type ViewerAssetFormat = "stl" | "gltf" | "glb"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => (window as any).emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
