
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<Result<Config, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConfig(config: Config) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels(provider: string, apiKey: string, baseUrl: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models", { provider, apiKey, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentModels(cmd: string) : Promise<Result<AgentModelList, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_models", { cmd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDesignSystemPrompt(provider: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_design_system_prompt", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppLogs() : Promise<Result<AppLogEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readComponentPackageManifest(projectDir: string) : Promise<Result<ComponentPackage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_component_package_manifest", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeComponentPackageManifest(projectDir: string, componentPackage: ComponentPackage) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_component_package_manifest", { projectDir, componentPackage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeArtifactBundleComponentPackageProject(projectDir: string, request: ArtifactBundleComponentPackageRequest) : Promise<Result<ComponentPackage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_artifact_bundle_component_package_project", { projectDir, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeComponentPackageArchive(projectDir: string, archivePath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_component_package_archive", { projectDir, archivePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readComponentPackageFromArchive(archivePath: string) : Promise<Result<ComponentPackage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_component_package_from_archive", { archivePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readComponentPackageHeaderFromArchive(archivePath: string) : Promise<Result<ComponentPackageHeader, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_component_package_header_from_archive", { archivePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractComponentPackageArchive(archivePath: string, targetDir: string) : Promise<Result<ComponentPackage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_component_package_archive", { archivePath, targetDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installComponentPackageArchive(archivePath: string) : Promise<Result<InstalledComponentPackage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_component_package_archive", { archivePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInstalledComponentPackageHeaders() : Promise<Result<ComponentPackageHeader[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_installed_component_package_headers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveInstalledComponentSource(packageId: string, version: string, componentId: string) : Promise<Result<InstalledComponentSource, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_installed_component_source", { packageId, version, componentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveInstalledComponentControls(packageId: string, version: string, componentId: string, parameters: Partial<{ [key in string]: ParamValue }>) : Promise<Result<InstalledComponentControls, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_installed_component_controls", { packageId, version, componentId, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveInstalledComponentAssembly(packageId: string, version: string, assemblyId: string) : Promise<Result<InstalledAssemblySource, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_installed_component_assembly", { packageId, version, assemblyId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveInstalledComponentAssemblyControls(packageId: string, version: string, assemblyId: string, instanceParameters: Partial<{ [key in string]: Partial<{ [key in string]: ParamValue }> }>) : Promise<Result<InstalledAssemblyControls, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_installed_component_assembly_controls", { packageId, version, assemblyId, instanceParameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderInstalledComponentSource(packageId: string, version: string, componentId: string, parameters: Partial<{ [key in string]: ParamValue }>) : Promise<Result<InstalledComponentRuntime, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_installed_component_source", { packageId, version, componentId, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderInstalledComponentAssembly(packageId: string, version: string, assemblyId: string, instanceParameters: Partial<{ [key in string]: Partial<{ [key in string]: ParamValue }> }>) : Promise<Result<InstalledAssemblyRuntime, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_installed_component_assembly", { packageId, version, assemblyId, instanceParameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportInstalledComponentAssembly3mf(packageId: string, version: string, assemblyId: string, instanceParameters: Partial<{ [key in string]: Partial<{ [key in string]: ParamValue }> }>, targetPath: string, modelName: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_installed_component_assembly_3mf", { packageId, version, assemblyId, instanceParameters, targetPath, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportInstalledComponentAssemblyMultipartStlZip(packageId: string, version: string, assemblyId: string, instanceParameters: Partial<{ [key in string]: Partial<{ [key in string]: ParamValue }> }>, targetPath: string, modelName: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_installed_component_assembly_multipart_stl_zip", { packageId, version, assemblyId, instanceParameters, targetPath, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory() : Promise<Result<Thread[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThread(id: string) : Promise<Result<Thread, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thread", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThreadLatestVersion(threadId: string) : Promise<Result<Message | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thread_latest_version", { threadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThreadMessageVersion(threadId: string, messageId: string) : Promise<Result<Message | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thread_message_version", { threadId, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThreadMessagesPage(threadId: string, before: number | null, limit: number | null, includeVisualPayloads: boolean) : Promise<Result<ThreadMessagesPage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thread_messages_page", { threadId, before, limit, includeVisualPayloads }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteThread(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_thread", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameThread(id: string, title: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_thread", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteVersion(messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_version", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreVersion(messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_version", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDeletedMessages() : Promise<Result<DeletedMessage[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_deleted_messages") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideDeletedMessage(messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_deleted_message", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async finalizeThread(id: string, messageId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finalize_thread", { id, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reopenThread(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reopen_thread", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInventory() : Promise<Result<Thread[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_inventory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThreadWindowLayout(threadId: string) : Promise<Result<ThreadWindowLayout | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thread_window_layout", { threadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveThreadWindowLayout(threadId: string, layout: ThreadWindowLayout) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_thread_window_layout", { threadId, layout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateDesign(prompt: string, threadId: string | null, parentMacroCode: string | null, workingDesign: DesignOutput | null, isRetry: boolean, imageData: string | null, attachments: Attachment[] | null, options: GenerateDesignOptions | null) : Promise<Result<GenerateOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_design", { prompt, threadId, parentMacroCode, workingDesign, isRetry, imageData, attachments, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initGenerationAttempt(threadId: string, prompt: string, attachments: Attachment[] | null, imageData: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_generation_attempt", { threadId, prompt, attachments, imageData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async finalizeGenerationAttempt(messageId: string, status: FinalizeStatus, design: DesignOutput | null, usage: UsageSummary | null, artifactBundle: ArtifactBundle | null, modelManifest: ModelManifest | null, errorMessage: string | null, responseText: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finalize_generation_attempt", { messageId, status, design, usage, artifactBundle, modelManifest, errorMessage, responseText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async classifyIntent(prompt: string, threadId: string | null, context: string | null, imageData: string | null, attachments: Attachment[] | null) : Promise<Result<IntentDecision, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("classify_intent", { prompt, threadId, context, imageData, attachments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyRender(originalPrompt: string, screenshots: string[], referenceImagePaths: string[], structuralSummary: string | null) : Promise<Result<VisualVerificationResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_render", { originalPrompt, screenshots, referenceImagePaths, structuralSummary }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyGeneratedModel(modelId: string, originalPrompt: string) : Promise<Result<StructuralVerificationResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_generated_model", { modelId, originalPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkFreecad() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_freecad") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRuntimeCapabilities() : Promise<Result<RuntimeCapabilities, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_runtime_capabilities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderStl(macroCode: string, parameters: Partial<{ [key in string]: ParamValue }>) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_stl", { macroCode, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderModel(macroCode: string, parameters: Partial<{ [key in string]: ParamValue }>, macroDialect: MacroDialect | null, geometryBackend: GeometryBackend | null, postProcessing: PostProcessingSpec | null) : Promise<Result<ArtifactBundle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_model", { macroCode, parameters, macroDialect, geometryBackend, postProcessing }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFcstd(sourcePath: string) : Promise<Result<ArtifactBundle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_fcstd", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchFreecadLibrary(request: FreecadLibrarySearchRequest) : Promise<Result<FreecadLibraryItem[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_freecad_library", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFreecadLibraryPart(request: FreecadLibraryImportRequest) : Promise<Result<ArtifactBundle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_freecad_library_part", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyImportedModel(artifactBundle: ArtifactBundle, manifest: ModelManifest, parameters: Partial<{ [key in string]: ParamValue }>, messageId: string | null) : Promise<Result<ArtifactBundle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_imported_model", { artifactBundle, manifest, parameters, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelManifest(modelId: string) : Promise<Result<ModelManifest, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_manifest", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractBrepHiddenLineProjections(request: BrepHiddenLineProjectionRequest) : Promise<Result<BrepHiddenLineProjectionResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_brep_hidden_line_projections", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveModelManifest(modelId: string, manifest: ModelManifest, messageId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_model_manifest", { modelId, manifest, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultMacro() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_macro") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMessStlPath() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mess_stl_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportFile(sourcePath: string, targetPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_file", { sourcePath, targetPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportMultipartStlZip(parts: ExportPartInput[], targetPath: string, modelName: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_multipart_stl_zip", { parts, targetPath, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportMultipart3mf(parts: ExportPartInput[], targetPath: string, modelName: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_multipart_3mf", { parts, targetPath, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateSketchDraftSource(request: SketchDraftRequest) : Promise<Result<SketchDraftSource, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_sketch_draft_source", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suggestSketchFeatures(request: SketchSuggestionRequest) : Promise<Result<SketchSuggestionResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_sketch_features", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateSketchDraftPreview(request: SketchDraftRequest) : Promise<Result<[SketchDraftSource, ArtifactBundle], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_sketch_draft_preview", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateSketchPreviewHull(request: SketchPreviewHullRequest) : Promise<Result<[SketchDraftSource, ArtifactBundle], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_sketch_preview_hull", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeSketchBrepCandidates(request: SketchBrepCandidateRequest) : Promise<Result<SketchBrepCandidateResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_sketch_brep_candidates", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async acceptedBrepCandidateToComponentPackage(request: SketchAcceptedBrepComponentPackageRequest) : Promise<Result<ComponentPackage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accepted_brep_candidate_to_component_package", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async acceptSketchBrepCandidateSolution(request: SketchBrepCandidateAcceptRequest) : Promise<Result<SketchBrepCandidateAcceptResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_sketch_brep_candidate_solution", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addManualVersion(input: AddManualVersionInput) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_manual_version", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addImportedModelVersion(threadId: string, title: string, artifactBundle: ArtifactBundle, modelManifest: ModelManifest) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_imported_model_version", { threadId, title, artifactBundle, modelManifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateUiSpec(messageId: string, uiSpec: UiSpec) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ui_spec", { messageId, uiSpec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateParameters(messageId: string, parameters: Partial<{ [key in string]: ParamValue }>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_parameters", { messageId, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessing(messageId: string, postProcessing: PostProcessingSpec | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_processing", { messageId, postProcessing }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateVersionRuntime(messageId: string, artifactBundle: ArtifactBundle, modelManifest: ModelManifest) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_version_runtime", { messageId, artifactBundle, modelManifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateVersionPreview(messageId: string, imageData: string, artifactBundle: ArtifactBundle) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_version_preview", { messageId, imageData, artifactBundle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async parseMacroParams(macroCode: string) : Promise<ParsedParamsResult> {
    return await TAURI_INVOKE("parse_macro_params", { macroCode });
},
async uploadAsset(sourcePath: string, name: string, format: string) : Promise<Result<Asset, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_asset", { sourcePath, name, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRecordedAudio(base64Data: string, name: string) : Promise<Result<Asset, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_recorded_audio", { base64Data, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribePromptAudio(input: TranscribePromptAudioInput) : Promise<Result<PromptTranscription, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_prompt_audio", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastDesign() : Promise<Result<LastDesignSnapshot | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_last_design") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveLastDesign(snapshot: LastDesignSnapshot | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_last_design", { snapshot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveAgentSessions() : Promise<Result<AgentSession[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_agent_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMcpServerStatus() : Promise<Result<McpServerStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mcp_server_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentTerminalSnapshots() : Promise<Result<AgentTerminalSnapshot[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_terminal_snapshots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendAgentTerminalInput(input: AgentTerminalInput) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_agent_terminal_input", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resizeAgentTerminal(agentId: string, cols: number, rows: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_agent_terminal", { agentId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async preparePromptAttachments(attachments: Attachment[]) : Promise<Result<Attachment[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_prompt_attachments", { attachments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async preparePromptWorkspaceCapture(input: PreparePromptWorkspaceCaptureInput) : Promise<Result<Attachment, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_prompt_workspace_capture", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMessageAttachments(messageId: string) : Promise<Result<Attachment[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_message_attachments", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queueAgentPrompt(input: QueueAgentPromptInput) : Promise<Result<QueuedAgentPrompt, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("queue_agent_prompt", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the frontend when the user clicks a confirmation button.
 * Resolves the pending oneshot channel so the MCP handler can return.
 */
async resolveAgentConfirm(requestId: string, choice: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_agent_confirm", { requestId, choice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the frontend when the user submits a prompt in MCP mode.
 * Resolves the pending oneshot channel so the MCP handler can return the text and attachments.
 */
async resolveAgentPrompt(input: ResolveAgentPromptInput) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_agent_prompt", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveAgentViewportScreenshot(input: ResolveViewportScreenshotInput) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_agent_viewport_screenshot", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rejectAgentViewportScreenshot(input: RejectViewportScreenshotInput) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_agent_viewport_screenshot", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current agent state for the given thread — for status bar display.
 */
async getThreadAgentState(threadId: string) : Promise<Result<ThreadAgentState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thread_agent_state", { threadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async wakePrimaryAutoAgent(threadId: string | null, messageId: string | null, modelId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wake_primary_auto_agent", { threadId, messageId, modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopPrimaryAutoAgent(threadId: string | null, messageId: string | null, modelId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_primary_auto_agent", { threadId, messageId, modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartPrimaryAutoAgent(threadId: string | null, messageId: string | null, modelId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_primary_auto_agent", { threadId, messageId, modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the frontend when the user queues a message in MCP mode and no agent is running.
 * Fires the wake notifier so the supervisor loop can respawn the named agent.
 * Safe to call redundantly — noop if the agent is already running.
 */
async wakeAutoAgent(label: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wake_auto_agent", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AddManualVersionInput = { threadId: string; title: string; versionName: string; macroCode: string; sourceLanguage: SourceLanguage | null; geometryBackend: GeometryBackend | null; parameters: Partial<{ [key in string]: ParamValue }>; uiSpec: UiSpec; postProcessing: PostProcessingSpec | null; artifactBundle: ArtifactBundle | null; modelManifest: ModelManifest | null }
export type Advisory = { advisoryId: string; label: string; severity: AdvisorySeverity; primitiveIds?: string[]; viewIds?: string[]; message: string; condition?: AdvisoryCondition; threshold?: number | null }
export type AdvisoryCondition = "always" | "below" | "above"
export type AdvisorySeverity = "info" | "warning"
export type AgentModelList = { models: string[]; isLive: boolean }
export type AgentOrigin = { hostLabel: string; clientKind: string; agentLabel: string; llmModelId?: string | null; llmModelLabel?: string | null; sessionId: string; createdAt: number }
export type AgentSession = { sessionId: string; clientKind: string; hostLabel: string; agentLabel: string; llmModelId?: string | null; llmModelLabel?: string | null; threadId: string | null; messageId: string | null; modelId: string | null; phase: string; statusText: string; updatedAt: number }
export type AgentTerminalInput = { agentId: string; text?: string; key?: string | null; ctrl?: boolean; alt?: boolean; shift?: boolean; meta?: boolean; submit?: boolean }
export type AgentTerminalSnapshot = { agentId: string; agentLabel: string; sessionId?: string | null; providerKind?: string | null; 
/**
 * Stable per-PTY-session token. Changes whenever the backend creates
 * a fresh terminal session for the agent.
 */
sessionNonce: number; 
/**
 * Deprecated compatibility snapshot for inactive/last-session display.
 * Live terminal rendering should use `vtStream`.
 */
screenText: string; 
/**
 * Authoritative raw VT replay stream for live terminal rendering.
 */
vtStream?: string; 
/**
 * Optional incremental VT chunk for live updates. When present, the frontend
 * should merge it into its local replay state instead of treating `vtStream`
 * as a full snapshot replacement.
 */
vtDelta?: string | null; attentionRequired: boolean; busy?: boolean; activityLabel?: string | null; activityStartedAt?: number | null; attentionKind?: string | null; summary?: string | null; active: boolean; updatedAt: number }
export type AppError = { code: AppErrorCode; message: string; details?: string | null }
export type AppErrorCode = "validation" | "notFound" | "conflict" | "provider" | "persistence" | "render" | "parse" | "internal"
export type AppLogEntry = { tsMs: number; message: string }
export type ArtifactBundle = { schemaVersion?: number; modelId: string; sourceKind: ModelSourceKind; engineKind?: EngineKind; sourceLanguage?: SourceLanguage; geometryBackend?: GeometryBackend; contentHash: string; artifactVersion?: number; fcstdPath: string; manifestPath: string; macroPath?: string | null; previewStlPath: string; viewerAssets?: ViewerAsset[]; edgeTargets?: ViewerEdgeTarget[]; faceTargets?: ViewerFaceTarget[]; calloutAnchors?: CalloutAnchor[]; measurementGuides?: MeasurementGuide[]; exportArtifacts?: ExportArtifact[] }
export type ArtifactBundleComponentPackageRequest = { packageId: string; version: string; displayName: string; tags?: string[]; componentId: string; componentVersion: string; componentDisplayName: string; sourceRef?: string | null; artifactBundle: ArtifactBundle; portTypes?: PortTypeDefinition[]; params?: ComponentParam[]; uiSpec?: UiSpec; initialParams?: Partial<{ [key in string]: ParamValue }>; ports?: ComponentPort[] }
export type AssemblyComponentRef = { instanceId: string; componentId: string }
export type AssemblyDefinition = { assemblyId: string; displayName: string; components?: AssemblyComponentRef[]; mates?: AssemblyMate[]; operations?: AssemblyOperation[]; output: AssemblyOutput }
export type AssemblyHeader = { assemblyId: string; displayName: string; componentCount: number; mateCount: number; operationCount: number; output: AssemblyOutput }
export type AssemblyMate = { mateId: string; typeId: string; a: PortReference; b: PortReference; params?: Partial<{ [key in string]: ComponentInterfaceValue }> }
export type AssemblyOperation = { operationId: string; kind: OperationKind; targetInstanceIds?: string[]; portRefs?: PortReference[]; params?: Partial<{ [key in string]: ComponentInterfaceValue }> }
export type AssemblyOutput = { mode: AssemblyOutputMode }
export type AssemblyOutputMode = "separateParts" | "joinedAssembly" | "fusedSolid" | "moldedSolid"
export type Asset = { id: string; name: string; path: string; format: string }
export type Attachment = { path: string; name: string; explanation: string; dataUrl?: string | null; kind: AttachmentKind }
export type AttachmentKind = "image" | "cad"
/**
 * Whether Ecky runs the embedded MCP HTTP server.
 */
export type AutoAgent = { id: string; label: string; cmd: string; model?: string | null; args: string[]; enabled: boolean; 
/**
 * Deprecated compatibility flag from the old eager-start implementation.
 * Active-mode wake behavior now depends on `mcp.mode` and `mcp.primaryAgentId`.
 */
startOnDemand?: boolean }
export type BrepHiddenLineProjectionRequest = { artifactBundle: ArtifactBundle; views?: SketchView[]; tolerance?: number | null; sketchDocument?: SketchDocument | null }
export type BrepHiddenLineProjectionResponse = { modelId: string; sourceArtifactPath: string; views?: BrepHiddenLineProjectionView[]; warningEntries?: BrepHiddenLineWarning[]; validation?: SketchBrepProjectionValidation | null }
export type BrepHiddenLineProjectionView = { view: SketchView; direction: [number, number, number]; visibleEdges?: BrepProjectedEdge2d[]; hiddenEdges?: BrepProjectedEdge2d[]; loops?: BrepProjectedLoop2d[] }
export type BrepHiddenLineWarning = { kind: BrepHiddenLineWarningKind; view: SketchView; message: string }
export type BrepHiddenLineWarningKind = "projectionNoEdges"
export type BrepProjectedEdge2d = { edgeId: string; points?: ([number, number])[]; sourceClass: string }
export type BrepProjectedLoop2d = { loopId: string; edgeIds?: string[]; points?: ([number, number])[]; role?: BrepProjectedLoopRole; sourceClass: string }
export type BrepProjectedLoopRole = "outer" | "hole" | "unknown"
export type CalloutAnchor = { anchorId: string; position: [number, number, number]; normal?: [number, number, number] | null }
export type ComponentDefinition = { componentId: string; version: string; displayName: string; sourceRef?: string | null; sourceLanguage?: SourceLanguage | null; geometryBackend?: GeometryBackend | null; macroDialect?: MacroDialect | null; sketches?: SketchDefinition[]; keepouts?: ComponentKeepoutVolume[]; fusionZones?: ComponentFusionZone[]; params?: ComponentParam[]; uiSpec?: UiSpec; initialParams?: Partial<{ [key in string]: ParamValue }>; ports?: ComponentPort[] }
export type ComponentFusionZone = { zoneId: string; surfaceRef: string; allowedOps?: OperationKind[]; maxBlendRadius?: number | null; keepoutIds?: string[] }
export type ComponentHeader = { componentId: string; version: string; displayName: string; params?: ComponentParam[]; uiSpec?: UiSpec; initialParams?: Partial<{ [key in string]: ParamValue }>; ports?: ComponentPort[] }
export type ComponentInterfaceValue = number | string | boolean
export type ComponentKeepoutVolume = { keepoutId: string; label: string; kind: KeepoutVolumeKind; frame?: PortFrame | null; size?: [number, number, number] | null; radius?: number | null; height?: number | null }
export type ComponentPackage = { schemaVersion?: number; packageId: string; version: string; displayName: string; visibility: PackageVisibility; tags?: string[]; portTypes?: PortTypeDefinition[]; mateTypes?: MateTypeDefinition[]; components?: ComponentDefinition[]; assemblies?: AssemblyDefinition[] }
export type ComponentPackageHeader = { schemaVersion: number; packageId: string; version: string; displayName: string; visibility: PackageVisibility; tags?: string[]; portTypes?: PortTypeDefinition[]; mateTypes?: MateTypeDefinition[]; components?: ComponentHeader[]; assemblies?: AssemblyHeader[] }
export type ComponentParam = { key: string; label: string; kind: ComponentParamKind; unit?: string | null }
export type ComponentParamKind = "number" | "text" | "boolean" | "choice"
export type ComponentPort = { portId: string; typeId: string; targetIds?: string[]; frame?: PortFrame | null; params?: Partial<{ [key in string]: ComponentInterfaceValue }>; interfaces?: string[]; compatibleWith?: string[]; allowedOps?: OperationKind[] }
export type Config = { engines: Engine[]; selectedEngineId: string; freecadCmd?: string; freecadLibraryRoots?: string[]; assets?: Asset[]; microwave?: MicrowaveConfig | null; voice?: VoiceConfig; mcp?: McpConfig; hasSeenOnboarding?: boolean; connectionType?: string | null; defaultEngineKind?: EngineKind; defaultSourceLanguage?: SourceLanguage; defaultGeometryBackend?: GeometryBackend; maxGenerationAttempts?: number; maxVerifyAttempts?: number }
export type ControlPrimitive = { primitiveId: string; label: string; kind: ControlPrimitiveKind; source?: ControlViewSource; partIds?: string[]; bindings?: PrimitiveBinding[]; editable: boolean; order?: number }
export type ControlPrimitiveKind = "number" | "toggle" | "choice"
export type ControlRelation = { relationId: string; sourcePrimitiveId: string; targetPrimitiveId: string; mode: ControlRelationMode; scale?: number; offset?: number; enabled?: boolean }
export type ControlRelationMode = "mirror" | "scale" | "offset"
export type ControlView = { viewId: string; label: string; scope: ControlViewScope; partIds?: string[]; primitiveIds?: string[]; sections?: ControlViewSection[]; default?: boolean; source?: ControlViewSource; status?: EnrichmentStatus; order?: number }
export type ControlViewScope = "global" | "part"
export type ControlViewSection = { sectionId: string; label: string; primitiveIds?: string[]; collapsed?: boolean }
export type ControlViewSource = "generated" | "inherited" | "llm" | "manual"
export type CorrespondenceEdge = { edgeId: string; source: FeatureOutputRef; target: FeatureOutputRef; relation: string; sourceRef?: SourceRef | null }
export type CorrespondenceGraph = { edges: CorrespondenceEdge[] }
export type DeletedMessage = { id: string; threadId: string; threadTitle: string; role: MessageRole; content: string; output?: DesignOutput | null; usage?: UsageSummary | null; artifactBundle?: ArtifactBundle | null; modelManifest?: ModelManifest | null; agentOrigin?: AgentOrigin | null; timestamp: number; imageData?: string | null; visualKind?: MessageVisualKind | null; attachmentImages?: string[]; deletedAt: number }
export type DesignOutput = { title?: string; versionName?: string; response?: string; interactionMode?: InteractionMode; macroCode: string; macroDialect?: MacroDialect; engineKind?: EngineKind; sourceLanguage?: SourceLanguage; geometryBackend?: GeometryBackend; uiSpec?: UiSpec; initialParams?: Partial<{ [key in string]: ParamValue }>; postProcessing?: PostProcessingSpec | null }
export type DisplacementSpec = { imageParam: string; projection: ProjectionType; depthMm: number; invert?: boolean }
export type DocumentMetadata = { documentName: string; documentLabel: string; sourcePath?: string | null; objectCount?: number; warnings?: string[] }
export type Engine = { id: string; name: string; provider: string; apiKey: string; model: string; lightModel?: string; baseUrl: string; enabled?: boolean }
export type EngineKind = "freecad" | "ecky" | "build123d"
export type EnrichmentProposal = { proposalId: string; label: string; partIds?: string[]; parameterKeys?: string[]; confidence: number; status: EnrichmentStatus; provenance: string }
export type EnrichmentStatus = "none" | "pending" | "accepted" | "rejected"
export type ExportArtifact = { label: string; format: string; path: string; role: string }
export type ExportPartInput = { label: string; path: string; objectName?: string | null; partId?: string | null; displayColor?: string | null; placementFrame?: PortFrame | null }
export type EyeStyle = "dot" | "bar" | "slant"
export type FeatureGraph = { nodes: FeatureNode[] }
export type FeatureNode = { featureId: string; kind: string; label: string; sourceRef?: SourceRef | null; dependencyIds: string[]; outputRefs: FeatureOutputRef[]; ports: FeaturePort[] }
export type FeatureOutputRef = { featureId: string; outputId: string; targetIds: string[] }
export type FeaturePort = { portId: string; typeId: string; targetIds: string[]; frame?: PortFrame | null; interfaces: string[]; params: Partial<{ [key in string]: ComponentInterfaceValue }>; sourceRef?: SourceRef | null; confidence?: number | null; targetRole?: string | null }
export type FinalizeStatus = "success" | "error" | "discarded"
export type FreecadLibraryImportRequest = { item: FreecadLibraryItem; threadId?: string | null; title?: string | null }
export type FreecadLibraryItem = { id: string; name: string; categoryPath: string; rootPath: string; relativePath: string; formats: string[]; preferredFormat: string; importPath: string; previewPath?: string | null; tags: string[] }
export type FreecadLibrarySearchRequest = { query: string; roots?: string[]; limit?: number | null; includeArchitecture?: boolean }
export type GenerateDesignOptions = { questionMode?: boolean | null; followUpQuestion?: string | null; engineKind?: EngineKind | null; sourceLanguage?: SourceLanguage | null; geometryBackend?: GeometryBackend | null }
export type GenerateOutput = { design: DesignOutput; threadId: string; messageId: string; usage?: UsageSummary | null }
export type GenieTraits = { version?: number; seed: number; colorHue: number; vertexCount: number; radiusBase: number; stretchY: number; asymmetry: number; chordSkip: number; jitterScale: number; pulseScale: number; hoverScale: number; warpScale: number; glowHueShift: number; eyeStyle: EyeStyle; eyeSpacing: number; eyeSize: number; mouthCurve: number; thinkingBias: number; repairBias: number; renderBias: number; expressiveness: number }
export type GeometryBackend = "freecad" | "build123d" | "mesh"
export type InstalledAssemblyComponentControls = { instanceId: string; componentId: string; parameters: Partial<{ [key in string]: ParamValue }>; placementFrame?: PortFrame | null; installedSource: InstalledComponentSource }
export type InstalledAssemblyComponentRuntime = { instanceId: string; componentId: string; parameters: Partial<{ [key in string]: ParamValue }>; placementFrame?: PortFrame | null; runtime: InstalledComponentRuntime }
export type InstalledAssemblyComponentSource = { instanceId: string; componentId: string; placementFrame?: PortFrame | null; installedSource: InstalledComponentSource }
export type InstalledAssemblyControls = { packageId: string; version: string; packageDisplayName: string; packageDir: string; assembly: AssemblyDefinition; portTypes?: PortTypeDefinition[]; mateTypes?: MateTypeDefinition[]; components?: InstalledAssemblyComponentControls[]; mateResults?: InstalledAssemblyMateResult[]; matesSolved?: boolean }
export type InstalledAssemblyMateResult = { mateId: string; solved: boolean; requiredClearance?: number | null; availableClearance?: number | null; warning?: string | null }
export type InstalledAssemblyOperationResult = { operationId: string; applied: boolean; groupId?: string | null; fusionZoneIdsByInstance?: Partial<{ [key in string]: string }>; warning?: string | null }
export type InstalledAssemblyOutputRuntime = { artifactBundle: ArtifactBundle; modelManifest: ModelManifest }
export type InstalledAssemblyRuntime = { packageId: string; version: string; packageDisplayName: string; packageDir: string; assembly: AssemblyDefinition; portTypes?: PortTypeDefinition[]; mateTypes?: MateTypeDefinition[]; components?: InstalledAssemblyComponentRuntime[]; mateResults?: InstalledAssemblyMateResult[]; matesSolved?: boolean; operationResults?: InstalledAssemblyOperationResult[]; operationsApplied?: boolean; outputRuntime?: InstalledAssemblyOutputRuntime | null; warnings?: string[] }
export type InstalledAssemblySource = { packageId: string; version: string; packageDisplayName: string; packageDir: string; assembly: AssemblyDefinition; portTypes?: PortTypeDefinition[]; mateTypes?: MateTypeDefinition[]; components?: InstalledAssemblyComponentSource[]; mateResults?: InstalledAssemblyMateResult[] }
export type InstalledComponentControls = { installedSource: InstalledComponentSource; parameters: Partial<{ [key in string]: ParamValue }> }
export type InstalledComponentPackage = { header: ComponentPackageHeader; packageDir: string }
export type InstalledComponentRuntime = { installedSource: InstalledComponentSource; parameters: Partial<{ [key in string]: ParamValue }>; artifactBundle: ArtifactBundle; modelManifest: ModelManifest }
export type InstalledComponentSource = { packageId: string; version: string; packageDisplayName: string; packageDir: string; component: ComponentDefinition; portTypes?: PortTypeDefinition[]; mateTypes?: MateTypeDefinition[]; sourcePath: string }
export type IntentDecision = { intentMode: string; confidence: number; response: string; finalResponse?: string | null; usage?: UsageSummary | null }
export type InteractionMode = "design" | "question" | "tune"
export type KeepoutVolumeKind = "box" | "cylinder" | "sphere" | "custom"
export type LastDesignSnapshot = { design?: DesignOutput | null; threadId?: string | null; messageId?: string | null; artifactBundle?: ArtifactBundle | null; modelManifest?: ModelManifest | null; selectedPartId?: string | null }
export type LithophaneAttachment = { id: string; enabled?: boolean; source: LithophaneAttachmentSource; targetPartId?: string; placement?: LithophanePlacement; relief?: LithophaneRelief; color?: LithophaneColor }
export type LithophaneAttachmentSource = { kind: "file"; imagePath: string } | { kind: "param"; imageParam: string }
export type LithophaneColor = { mode?: LithophaneColorMode; channelThicknessMm?: number }
export type LithophaneColorMode = "mono" | "cmyk"
export type LithophanePlacement = { mode?: LithophanePlacementMode; side?: LithophaneSide; projection?: ProjectionType; widthMm?: number; heightMm?: number; offsetXMm?: number; offsetYMm?: number; rotationDeg?: number; overflowMode?: OverflowMode; bleedMarginMm?: number }
export type LithophanePlacementMode = "partSidePatch"
export type LithophaneRelief = { depthMm?: number; invert?: boolean }
export type LithophaneSide = "front" | "back" | "left" | "right" | "top" | "bottom"
export type MacroDialect = "legacy" | "cadFrameworkV1" | "ecky" | "build123d"
export type ManifestBounds = { xMin: number; yMin: number; zMin: number; xMax: number; yMax: number; zMax: number }
export type ManifestEnrichmentState = { status: EnrichmentStatus; proposals?: EnrichmentProposal[] }
export type MatePortTypePair = { aTypeId: string; bTypeId: string }
export type MateTypeDefinition = { typeId: string; displayName: string; allowedPortTypePairs?: MatePortTypePair[]; params?: ComponentParam[] }
export type McpConfig = { 
/**
 * HTTP port for the MCP server. Defaults to 39249.
 */
port?: number | null; 
/**
 * Max concurrent agent sessions. None = unlimited.
 */
maxSessions?: number | null; 
/**
 * How Ecky exposes MCP: passive server-only or active server + lazy auto-agent wake.
 */
mode?: McpMode; 
/**
 * Which auto-agent should be woken when the user queues a message in active mode.
 */
primaryAgentId?: string | null; 
/**
 * Default request_user_prompt timeout used when the agent does not pass timeoutSecs.
 */
promptTimeoutSecs?: number; 
/**
 * Experimental: expose read-only Ecky Core AST tools for agent authoring.
 */
eckyAstAuthoring?: boolean; 
/**
 * External processes available to Ecky in active mode.
 */
autoAgents?: AutoAgent[] }
export type McpMode = "passive" | "active"
export type McpServerStatus = { running: boolean; endpointUrl: string; lastStartupError?: string | null }
export type MeasurementAnnotation = { annotationId: string; label: string; basis: MeasurementBasis; axis: MeasurementAxis; parameterKeys?: string[]; primitiveIds?: string[]; targetIds?: string[]; guideId?: string | null; explanation?: string | null; formulaHint?: string | null; source: MeasurementAnnotationSource }
export type MeasurementAnnotationSource = "generated" | "llm" | "manual" | "api"
export type MeasurementAxis = "x" | "y" | "z" | "radial" | "normal" | "path" | "custom"
export type MeasurementBasis = "outer" | "inner" | "wall" | "clearance" | "centerline" | "pitch" | "custom"
export type MeasurementGuide = { guideId: string; kind: MeasurementGuideKind; anchorIds?: string[]; labelAnchorId?: string | null; targetIds?: string[] }
export type MeasurementGuideKind = "linear" | "radial" | "clearance" | "pitch" | "leader"
export type Message = { id: string; role: MessageRole; content: string; status: MessageStatus; output?: DesignOutput | null; usage?: UsageSummary | null; artifactBundle?: ArtifactBundle | null; modelManifest?: ModelManifest | null; agentOrigin?: AgentOrigin | null; imageData?: string | null; visualKind?: MessageVisualKind | null; attachmentImages?: string[]; timestamp: number }
export type MessageRole = "user" | "assistant"
export type MessageStatus = "pending" | "working" | "success" | "error" | "discarded"
export type MessageVisualKind = "conceptPreview"
export type MicrowaveConfig = { humId?: string | null; dingId?: string | null; muted?: boolean }
export type ModelManifest = { schemaVersion?: number; modelId: string; sourceKind: ModelSourceKind; sourceDigest?: string | null; coreDigest?: string | null; astSchemaVersion?: number | null; engineKind?: EngineKind; sourceLanguage?: SourceLanguage; geometryBackend?: GeometryBackend; document: DocumentMetadata; parts?: PartBinding[]; parameterGroups?: ParameterGroup[]; controlPrimitives?: ControlPrimitive[]; controlRelations?: ControlRelation[]; controlViews?: ControlView[]; advisories?: Advisory[]; selectionTargets?: SelectionTarget[]; measurementAnnotations?: MeasurementAnnotation[]; featureGraph?: FeatureGraph | null; correspondenceGraph?: CorrespondenceGraph | null; warnings?: string[]; enrichmentState?: ManifestEnrichmentState }
export type ModelSourceKind = "generated" | "importedFcstd" | "importedStep" | "importedMesh"
export type OperationKind = "place" | "mate" | "join" | "cut" | "fuse" | "mold" | "blend"
export type OverflowMode = "contain" | "cover" | "clamp" | "bleed"
export type PackageVisibility = "source" | "compiled" | "locked" | "private"
export type ParamValue = string | number | boolean | null
export type ParameterGroup = { groupId: string; label: string; parameterKeys?: string[]; partIds?: string[]; editable: boolean; presentation?: string | null; order?: number | null }
export type ParsedParamsResult = { fields: UiField[]; params: Partial<{ [key in string]: ParamValue }> }
export type PartBinding = { partId: string; freecadObjectName: string; label: string; kind: string; semanticRole?: string | null; viewerAssetPath?: string | null; viewerNodeIds?: string[]; parameterKeys?: string[]; editable: boolean; bounds?: ManifestBounds | null; volume?: number | null; area?: number | null }
export type PortFrame = { origin: [number, number, number]; xAxis: [number, number, number]; yAxis: [number, number, number]; zAxis: [number, number, number] }
export type PortReference = { instanceId: string; portId: string }
export type PortTypeDefinition = { typeId: string; displayName: string; base?: string | null; interfaces?: string[]; compatibleWith?: string[]; allowedOps?: OperationKind[]; params?: ComponentParam[] }
export type PostProcessingSpec = { displacement?: DisplacementSpec | null; lithophaneAttachments?: LithophaneAttachment[] }
export type PreparePromptWorkspaceCaptureInput = { dataUrl: string; threadId?: string | null; name?: string | null; explanation?: string | null }
export type PrimitiveBinding = { parameterKey: string; scale?: number; offset?: number; min?: number | null; max?: number | null }
export type ProjectionType = "planar" | "auto" | "cylindrical" | "spherical"
export type PromptTranscription = { text: string; provider: string; model: string }
export type QueueAgentPromptInput = { threadId?: string | null; promptText: string; attachments?: Attachment[] }
export type QueuedAgentPrompt = { threadId: string; messageId: string }
export type RejectViewportScreenshotInput = { requestId: string; error: string }
export type ResolveAgentPromptInput = { requestId: string; promptText: string; messageIds: string[]; messageId?: string | null; attachments?: Attachment[] }
export type ResolveViewportScreenshotInput = { requestId: string; dataUrl: string; width: number; height: number; camera: ViewportCameraState; source: string; threadId: string; messageId: string; modelId?: string | null; includeOverlays: boolean }
export type RuntimeAuthoringContext = { engineKind: EngineKind; sourceLanguage: SourceLanguage; geometryBackend: GeometryBackend }
export type RuntimeBackendCapability = { available: boolean; detail: string; path?: string | null }
export type RuntimeCapabilities = { freecad: RuntimeBackendCapability; build123D: RuntimeBackendCapability; directOcct: RuntimeBackendCapability; mesh: RuntimeBackendCapability; recommendedAuthoringContext: RuntimeAuthoringContext }
export type SelectOption = { label: string; value: SelectValue }
export type SelectValue = string | number
export type SelectionTarget = { targetId?: string | null; durableTargetId?: string | null; canonicalTargetId?: string | null; aliasIds?: string[]; partId: string; viewerNodeId: string; label: string; kind: SelectionTargetKind; editable: boolean; parameterKeys?: string[]; primitiveIds?: string[]; viewIds?: string[] }
export type SelectionTargetKind = "part" | "object" | "group" | "edge" | "face"
export type SketchAcceptedBrepComponentPackageRequest = { packageId: string; version: string; displayName: string; tags?: string[]; componentId: string; componentVersion: string; componentDisplayName: string; sourceRef: string; artifactBundle?: ArtifactBundle | null; document: SketchDocument; solutionId: string; portTypes?: PortTypeDefinition[]; params?: ComponentParam[]; uiSpec?: UiSpec; initialParams?: Partial<{ [key in string]: ParamValue }>; ports?: ComponentPort[] }
export type SketchBrepCandidateAcceptRequest = { partId: string; document: SketchDocument; solutionId: string; tolerance?: number | null }
export type SketchBrepCandidateAcceptResponse = { draftSource: SketchDraftSource; artifactBundle: ArtifactBundle; hiddenLineResponse: BrepHiddenLineProjectionResponse; candidateResponse: SketchBrepCandidateResponse; acceptedSolution: SketchBrepCandidateSolution; evidence?: string[] }
export type SketchBrepCandidateCell = { cellId: string; min: [number, number, number]; max: [number, number, number]; supportViews?: SketchView[] }
export type SketchBrepCandidateEdge = { edgeId: string; a: string; b: string; supportViews?: SketchView[] }
export type SketchBrepCandidateGraph = { vertices?: SketchBrepCandidateVertex[]; edges?: SketchBrepCandidateEdge[] }
export type SketchBrepCandidateRequest = { document: SketchDocument }
export type SketchBrepCandidateResponse = { graph: SketchBrepCandidateGraph; search: SketchBrepCandidateSearch; validation: SketchBrepProjectionValidation }
export type SketchBrepCandidateSearch = { cells?: SketchBrepCandidateCell[]; rejectedCellCount?: number; solutions?: SketchBrepCandidateSolution[]; evidence?: string[] }
export type SketchBrepCandidateSolution = { solutionId: string; cellIds?: string[]; score: number; sourceStrategy?: SketchBrepCandidateSourceStrategy; evidence?: string[] }
export type SketchBrepCandidateSourceStrategy = "cellUnion" | "frontProfilePrism"
export type SketchBrepCandidateVertex = { vertexId: string; point: [number, number, number]; evidenceViews?: SketchView[] }
export type SketchBrepProjectionValidation = { passed: boolean; issues?: SketchValidationIssue[]; evidence?: string[] }
export type SketchConstraint = { constraintId: string; kind: SketchConstraintKind; targetIds?: string[]; value?: number | null }
export type SketchConstraintKind = "closed" | "horizontal" | "vertical" | "tangent" | "equal" | "symmetric" | "dimension"
export type SketchDefinition = { sketchId: string; view: SketchView; plane?: PortFrame | null; primitives?: SketchPrimitive[]; constraints?: SketchConstraint[] }
export type SketchDocument = { documentId: string; sketches?: SketchDefinition[]; activeSketchId?: string | null; units?: string | null; metadata?: Partial<{ [key in string]: string }> | null }
export type SketchDraftOperationKind = "extrude" | "revolve"
export type SketchDraftRequest = { partId: string; sketch: SketchDefinition; operation: SketchDraftOperationKind; amount: number; symmetric?: boolean }
export type SketchDraftSource = { sourceLanguage: SourceLanguage; geometryBackend: GeometryBackend; macroDialect: MacroDialect; source: string; warnings?: string[] }
export type SketchFeatureSuggestion = { suggestionId: string; sketchId: string; primitiveId?: string | null; partId: string; operation: SketchDraftOperationKind; amount: number; symmetric?: boolean; confidence: number; reason: string; warnings?: string[] }
export type SketchPreviewHullRequest = { partId: string; document: SketchDocument; fallbackDepth: number }
export type SketchPrimitive = { primitiveId: string; kind: SketchPrimitiveKind; points?: ([number, number])[]; closed?: boolean; radius?: number | null; topology?: SketchPrimitiveTopology | null }
export type SketchPrimitiveKind = "point" | "line" | "polyline" | "spline" | "arc" | "circle"
export type SketchPrimitiveTopology = { loopId?: string | null; edgeIds?: string[]; loopRole?: BrepProjectedLoopRole | null; sourceClass?: string | null }
export type SketchSuggestionRequest = { document: SketchDocument; limit?: number | null }
export type SketchSuggestionResponse = { suggestions?: SketchFeatureSuggestion[]; warnings?: string[] }
export type SketchValidationIssue = { sketchId: string; kind: SketchValidationIssueKind; view: SketchView; primitiveId?: string | null; edgeId?: string | null; topology?: SketchPrimitiveTopology | null; severity: SketchValidationSeverity; message: string }
export type SketchValidationIssueKind = "missingClosedProfile" | "missingProjectionEdges" | "boundsMismatch" | "containmentMismatch" | "topologyMismatch" | "concavityMismatch" | "projectionReplayCoverageGap" | "candidateGraphNoVertices" | "candidateGraphNoEdges"
export type SketchValidationSeverity = "warning" | "error"
export type SketchView = "front" | "side" | "top" | "custom"
export type SourceLanguage = "legacyPython" | "ecky" | "build123d"
export type SourceRef = { sourceId?: string | null; path?: string | null; startByte?: number | null; endByte?: number | null }
export type StructuralIssue = { code: string; message: string; 
/**
 * ID of the affected part, when the issue is part-specific.
 */
partId?: string | null; numericPayload?: number | null }
export type StructuralMetrics = { partCount: number; previewStlSizeBytes?: number | null; previewStlTriangleCount?: number | null; previewStlComponentCount?: number | null; previewStlNonManifoldEdgeCount?: number | null; previewStlOverhangTriangleCount?: number | null; previewStlOverhangRatio?: number | null; totalVolume?: number | null; totalArea?: number | null; bbox?: ManifestBounds | null }
export type StructuralVerificationResult = { passed: boolean; summary: string; issues: StructuralIssue[]; metrics: StructuralMetrics; verifierStatus: VerifierStatus; verifierSource?: VerifierSource | null }
export type Thread = { id: string; title: string; summary?: string; messages: Message[]; updatedAt: number; genieTraits?: GenieTraits | null; versionCount?: number; pendingCount?: number; queuedCount?: number; errorCount?: number; status?: ThreadStatus; finalizedAt?: number | null; pendingConfirm?: string | null }
export type ThreadAgentState = { 
/**
 * "none" | "sleeping" | "waking" | "waiting" | "active" | "disconnected" | "error"
 */
connectionState: string; agentLabel: string | null; llmModelLabel: string | null; providerKind?: string | null; sessionId?: string | null; phase: string | null; statusText: string | null; busy?: boolean; activityLabel?: string | null; activityStartedAt?: number | null; attentionKind?: string | null; waitingOnPrompt?: boolean; updatedAt: number | null }
export type ThreadMessagesPage = { messages: Message[]; nextBefore: number | null; hasMore: boolean }
export type ThreadStatus = "active" | "finalized"
export type ThreadWindowLayout = { schemaVersion?: number; rememberLayout?: boolean; windows: Partial<{ [key in string]: ThreadWindowState }> }
export type ThreadWindowState = { visible: boolean; minimized?: boolean; x: number; y: number; width: number; height: number; z: number }
export type TranscribePromptAudioInput = { base64Data: string; mimeType: string; languageCode?: string | null }
export type UiField = { type: "range"; key: string; label?: string; min?: number | null; max?: number | null; step?: number | null; minFrom?: string | null; maxFrom?: string | null; frozen?: boolean } | { type: "number"; key: string; label?: string; min?: number | null; max?: number | null; step?: number | null; minFrom?: string | null; maxFrom?: string | null; frozen?: boolean } | { type: "select"; key: string; label?: string; options?: SelectOption[]; frozen?: boolean } | { type: "checkbox"; key: string; label?: string; frozen?: boolean } | { type: "image"; key: string; label?: string; frozen?: boolean }
export type UiSpec = { fields?: UiField[] }
export type UsageSegment = { stage: string; provider: string; model: string; inputTokens?: number; outputTokens?: number; totalTokens?: number; cachedInputTokens?: number; reasoningTokens?: number; estimatedCostUsd?: number | null }
export type UsageSummary = { inputTokens?: number; outputTokens?: number; totalTokens?: number; cachedInputTokens?: number; reasoningTokens?: number; estimatedCostUsd?: number | null; segments?: UsageSegment[] }
export type VerifierSource = "rust_structural" | "rust_plus_backend"
export type VerifierStatus = "ok" | "ok_rust_only" | "ok_with_backend" | "skipped_unavailable" | "skipped_backend_unavailable"
export type ViewerAsset = { partId: string; nodeId: string; objectName: string; label: string; path: string; format: ViewerAssetFormat }
export type ViewerAssetFormat = "stl" | "gltf" | "glb" | "obj" | "3mf"
export type ViewerEdgePoint = { x: number; y: number; z: number }
export type ViewerEdgeTarget = { targetId: string; durableTargetId?: string | null; canonicalTargetId?: string | null; aliasIds: string[]; partId: string; viewerNodeId: string; label: string; editable: boolean; start: ViewerEdgePoint; end: ViewerEdgePoint }
export type ViewerFaceTarget = { targetId: string; durableTargetId?: string | null; canonicalTargetId?: string | null; aliasIds: string[]; partId: string; viewerNodeId: string; label: string; editable: boolean; center: ViewerEdgePoint; normal?: [number, number, number] | null; area?: number | null }
export type ViewportCameraState = { position: [number, number, number]; target: [number, number, number]; zoom?: number | null; fov?: number | null }
export type VisualIssue = { category: VisualIssueCategory; description: string; partLabel?: string | null }
export type VisualIssueCategory = "missing_part" | "floating_part" | "connector_broken" | "reference_mismatch" | "topology_broken" | "other"
export type VisualVerificationResult = { passed: boolean; summary: string; issues: VisualIssue[]; usage?: UsageSummary | null }
export type VoiceConfig = { sttLanguageCode?: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => (window as any).emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
